apiVersion: v1
kind: Service
metadata:
  name: hello-springboot
  labels:
    app: hello-springboot
    book: microservices4javadev
spec:
  ports:
  - name: http
    port: 8080
  selector:
    app: hello-springboot